os:
  editCommmand: 'nvim'
  editCommandTemplate: '{{editor}} +{{line}} -- {{filename}}'

gui:
  expandFocusedSidePanel: true
  showIcons: true
  authorColors:
    'Quy Nguyen': '#0000FF'
    '*': '#A020F0'
